'use client'
import "./globals.css";
import Header from "./components/Header";
import FooterComp from "./components/Footer";



const metadata = {
  title: "Project Proposal Similarity Checker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
     <html lang="en">
      <body
  
      >
        <Header/>
        {children}
        <FooterComp/>
      </body>
    </html>
  );
}
