
import "./globals.css";
import Header from "./components/Header";
import FooterComp from "./components/Footer";
import { UserProvider } from "./auth/AuthContext";

export const metadata = {
  title: "Project Proposal Similarity Checker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
     <html lang="en">
      <body>
        <UserProvider>
        <Header/>
        {children}
        <FooterComp/>
        </UserProvider>
      </body>
    </html>
  );
}
